import { SpotifyProvider } from '@/context/SpotifyContext';

export const metadata = {
  title: "Spotify Top Songs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <SpotifyProvider>
            <html lang="en">
            <body>{children}</body>
            </html>
        </SpotifyProvider>
    );
}

